[default]
template_dir = "static"
port = 80
address = "0.0.0.0"

chains = [
	{ id = "ubiknetwork-1", api = "http://178.18.242.126:26657", prefix = "ubik", denom = "uubik" },
	{ id = "cosmoshub-testnet", api = "http://161.97.65.58:26657", prefix = "cosmos", denom = "uphoton" },
]